name: Test and Build

on:
  push:
    branches:
      - master

jobs:
  test:
    name: Test Python Application
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.9"]

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Python
    - name: Setup Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    # Cache dependencies
    # - name: Cache pip packages
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/.cache/pip
    #     key: ${{ env.CACHE_KEY }}
    #     restore-keys: |
    #       ${{ runner.os }}-pip-

    # Install dependencies
    - name: Install Dependencies
      run: |
        if [ -f requirements.txt ]; then
          pip install --upgrade pip
          pip install -r requirements.txt
        else
          echo "requirements.txt not found, skipping dependency installation."
          exit 1
        fi

    # Run tests
    - name: Run Tests
      run: |
        if [ -f pytest.ini ] || [ -d tests ]; then
          python -m pytest
        else
          echo "No tests detected."
          exit 1
        fi
