name: Test and Build
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies and run tests
        run: |
          if [ -d "tests" ]; then
            echo "Tests directory found, running tests..."
            pip install pytest
            python -m pytest tests/
          else
            echo "No tests directory found, skipping tests"
          fi

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Build project
        run: |
          if [ -f "pyproject.toml" ] || [ -f "setup.py" ] || [ -f "setup.cfg" ] ; then
            echo "Build configuration found, building..."
            pip install build
            python -m build
            [ -d "dist" ] && echo "Build successful"
          else
            echo "No build configuration found, skipping build"
          fi
      - name: Upload artifacts
        if: hashFiles('dist/**') != ''
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: dist/
