name: Test and Build
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          fi
          pip install pytest
          # If you have a setup.py or pyproject.toml:
          # pip install -e .
      
      - name: Run tests
        run: |
          if [ -d "tests" ]; then
            echo "Tests directory found, running tests..."
            python -m pytest tests/ -v
          else
            echo "No tests directory found, skipping tests"
          fi
