name: Test and Build

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Package Python Application
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Python
    - name: Setup Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    # Install build dependencies
    - name: Install Build Dependencies
      run: |
        pip install --upgrade pip
        pip install build

    # Build Python package
    - name: Build Package
      run: |
        if [ -f setup.py ]; then
          python -m build
        else
          echo "setup.py not found, skipping build."
          exit 1
        fi
